version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /app
        volumes:
            - ./:/app
        depends_on:
            - mysql
            - nginx
        networks:
            - laravel
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8008:80"
        volumes:
            - ./:/app
            - ./docker/nginx/:/etc/nginx/conf.d
        networks:
            - laravel

    mysql:
        container_name: db
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE-laravel}
            MYSQL_USER: ${MYSQL_USER-laravel}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD-laravel}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD-root}
        ports:
            - "3308:3306"
        networks:
            - laravel
networks:
    laravel:
        name: laravel
        driver: bridge
